sensor:
  - platform: homeassistant
    entity_id: sensor.lounge_room_temperature_temperature
    id: lounge_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(x)', '(int)round(id(lounge_humidity).state)' ]

  - platform: homeassistant
    entity_id: sensor.lounge_room_temperature_humidity
    id: lounge_humidity
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(id(lounge_temperature).state)', '(int)round(x)' ]


binary_sensor:
  - platform: homeassistant
    id: nightstand_lamp_state
    entity_id: light.nightstand_lamp
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: nightstand_lamp_button
            state:
              checked: !lambda return x;

  - platform: homeassistant
    id: bedroom_lamp_1_state
    entity_id: light.bedroom_lamp_1
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: bedroom_lamp_1_button
            state:
              checked: !lambda return x;

  - platform: homeassistant
    id: bedroom_lamp_2_state
    entity_id: light.bedroom_lamp_2
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: bedroom_lamp_2_button
            state:
              checked: !lambda return x;

  - platform: homeassistant
    id: dresser_lamp_state
    entity_id: light.dresser_lamp
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: dresser_lamp_button
            state:
              checked: !lambda return x;