binary_sensor:
  - platform: homeassistant
    id: blue_lamp_state
    entity_id: light.blue_lamp
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: blue_lamp_button
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: lounge_bulb_1_state
    entity_id: light.lounge_bulb_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lounge_bulb_1_button
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: lounge_bulb_2_state
    entity_id: light.lounge_bulb_2
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lounge_bulb_2_button
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: lounge_bulb_3_state
    entity_id: light.lounge_bulb_3
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lounge_bulb_3_button
          state:
            checked: !lambda return x;