sensor:
  - platform: homeassistant
    entity_id: sensor.lounge_room_temperature_temperature
    id: lounge_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(x)', '(int)round(id(lounge_humidity).state)' ]

  - platform: homeassistant
    entity_id: sensor.lounge_room_temperature_humidity
    id: lounge_humidity
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d%%"
            args: [ '(int)round(id(lounge_temperature).state)', '(int)round(x)' ]


binary_sensor:
  - platform: homeassistant
    id: blue_lamp_state
    entity_id: light.blue_lamp
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: blue_lamp_button
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: lounge_bulb_1_state
    entity_id: light.lounge_bulb_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lounge_bulb_1_button
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: lounge_bulb_2_state
    entity_id: light.lounge_bulb_2
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lounge_bulb_2_button
          state:
            checked: !lambda return x;

  - platform: homeassistant
    id: lounge_bulb_3_state
    entity_id: light.lounge_bulb_3
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lounge_bulb_3_button
          state:
            checked: !lambda return x;
                   
  - platform: homeassistant
    id: wiim_muted
    entity_id: media_player.living_room_wiim
    attribute: is_volume_muted
    trigger_on_initial_state: true
    on_state:
      then:
        - lvgl.widget.update:
            id: wiim_mute_button
            state:
              checked: !lambda return x;
            
 
text_sensor:
  - platform: homeassistant
    entity_id: media_player.living_room_wiim
    attribute: entity_picture
    id: wiim_art_url
    on_value:
      then:
        - online_image.set_url:
            id: wiim_album_art
            url: !lambda 'return x;'
        - component.update: wiim_album_art
        
  - platform: homeassistant
    entity_id: media_player.living_room_wiim
    attribute: media_title
    id: wiim_media_title
    on_value:
      - lvgl.label.update:
          id: wiim_title_label
          text: !lambda |-
            if (x.empty()) return std::string("Silencio");
            return x;

  - platform: homeassistant
    entity_id: media_player.living_room_wiim
    attribute: media_artist
    id: wiim_media_artist
    on_value:
      - lvgl.label.update:
          id: wiim_artist_label
          text: !lambda |-
            if (x.empty()) return std::string("");
            return x;

  - platform: homeassistant
    entity_id: media_player.living_room_wiim
    attribute: media_album_name
    id: wiim_media_album
    on_value:
      - lvgl.label.update:
          id: wiim_album_label
          text: !lambda |-
            if (x.empty()) return std::string("");
            return x;

  - platform: homeassistant
    entity_id: media_player.living_room_wiim
    attribute: source
    id: wiim_source
    on_value:
      - lvgl.label.update:
          id: wiim_source_label
          text: !lambda |-
            if (x.empty()) return std::string("Source: --");
            return std::string("Source: ") + x;